version: '3.9'

services:
  database:
    image: postgres
    container_name: database_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=apidb
      - POSTGRES_DB=api_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: api_app
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database  

volumes:
  pgdata:
    driver: local